# Generated by Django 3.2.15 on 2022-10-26 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ('name',), 'verbose_name': 'Плейлист', 'verbose_name_plural': 'Плейлисты'},
        ),
    ]
