# Generated by Django 3.2.15 on 2022-09-10 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='musician',
            options={'ordering': ('last_name',)},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ('written', 'name')},
        ),
    ]
