# Generated by Django 3.2.15 on 2022-10-30 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='patronymic',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Отчество'),
        ),
    ]
