# Generated by Django 3.2.15 on 2022-09-10 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_auto_20220910_0759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('name',), 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='musician',
            options={'ordering': ('last_name',), 'verbose_name': 'Музыкант', 'verbose_name_plural': 'Музыканты'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ('written', 'name'), 'verbose_name': 'Песня', 'verbose_name_plural': 'Песни'},
        ),
    ]
