# Generated by Django 3.2.15 on 2022-09-10 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('musics', '0003_auto_20220910_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Человекопонятная ссылка')),
                ('description', models.TextField(blank=True, verbose_name='Биография')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Дата смерти')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ('name',),
            },
        ),
        migrations.RenameField(
            model_name='song',
            old_name='object_id',
            new_name='artist_id',
        ),
        migrations.RemoveField(
            model_name='song',
            name='content_type',
        ),
        migrations.AddField(
            model_name='song',
            name='artist_type',
            field=models.ForeignKey(default=1, limit_choices_to={'model__in': ('musician', 'music_group')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='musician',
            name='date_of_birth',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='Дата смерти'),
        ),
        migrations.AlterField(
            model_name='song',
            name='written',
            field=models.DateField(verbose_name='Написана'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.AddField(
            model_name='musicgroup',
            name='musicians',
            field=models.ManyToManyField(related_name='music_groups', to='musics.Musician', verbose_name='Музыканты'),
        ),
    ]
