# Generated by Django 3.2.15 on 2022-09-10 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('musics', '0004_auto_20220910_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('musician', 'musicgroup')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
