# Generated by Django 3.2.15 on 2022-11-04 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Тип')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
            ],
            options={
                'ordering': ('type',),
            },
        ),
        migrations.AlterField(
            model_name='premium',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.premiumtype', verbose_name='Тип'),
        ),
    ]
