# Generated by Django 3.2.15 on 2022-11-04 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20221104_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='premiumtype',
            options={'ordering': ('type',), 'verbose_name': 'Тип премиум-аккаунта', 'verbose_name_plural': 'Типы премиум-аккаунтов'},
        ),
    ]
