# Generated by Django 3.2.15 on 2022-11-04 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0003_alter_premiumtype_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premium',
            name='discount',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premium', to='payments.discount', verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='premium',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premiums', to='payments.premiumtype', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promos', to='payments.discount', verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo',
            field=models.CharField(blank=True, max_length=64, verbose_name='Промокод'),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата сделки')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receipts', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
                ('premium', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receipts', to='payments.premium', verbose_name='Премиум')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
                'ordering': ('-transaction_date',),
            },
        ),
    ]
