# Generated by Django 3.2.15 on 2022-11-04 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20221104_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='discount',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='payments.discount', verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='premium_end_date',
            field=models.DateTimeField(null=True, verbose_name='Дата окончания премиума'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='premium',
            name='discount',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premiums', to='payments.discount', verbose_name='Скидка'),
        ),
    ]
