# Generated by Django 3.2.15 on 2022-11-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20221104_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumtype',
            name='private_playlists',
            field=models.PositiveIntegerField(default=5, verbose_name='Количество скрытых плейлистов'),
        ),
        migrations.AddField(
            model_name='premiumtype',
            name='public_playlists',
            field=models.PositiveIntegerField(default=8, verbose_name='Количество публичных плейлистов'),
        ),
    ]
