# Generated by Django 3.2.15 on 2022-11-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20221104_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumtype',
            name='level',
            field=models.PositiveIntegerField(default=0, verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='premiumtype',
            name='songs_per_playlist',
            field=models.PositiveIntegerField(default=50, verbose_name='Максимальное количество песен в плейлисте'),
        ),
    ]
