# Generated by Django 3.2.15 on 2022-11-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20221107_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='premium',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
