# Generated by Django 3.2.15 on 2022-11-07 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_premium_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premium',
            name='discount',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premiums', to='payments.discount', verbose_name='Скидка'),
        ),
    ]
