# Generated by Django 3.2.15 on 2022-10-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(default=0, unique=True, verbose_name='Человекопонятная ссылка'),
            preserve_default=False,
        ),
    ]
